include:
    - template: Jobs/SAST.gitlab-ci.yml

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: '/certs'
    SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    SSH_PUBLIC_KEY: ${SSH_PUBLIC_KEY}
    DOCKER_HOST: tcp://docker:2375

stages:
    - build
    - test
    - deploy

code_tests:
    stage: test
    image: golang:1.19
    before_script:
        - go mod download
    script:
        - go test -race ./...

code_linter:
    stage: test
    image: golangci/golangci-lint:v1.50.1
    before_script:
        - go mod download
    script:
        - golangci-lint run ./...
