CREATE TABLE IF NOT EXISTS order_lists (
    id serial PRIMARY KEY,
    date_order DATE NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    public_procurement_id INTEGER NOT NULL,
    supplier_id INTEGER,
    status TEXT NOT NULL,
    date_system DATE,
    delivery_number TEXT,
    delivery_date DATE,
    delivery_file_id INTEGER,
    invoice_date DATE,
    pro_forma_invoice_date DATE,
    pro_forma_invoice_number TEXT,
    invoice_number TEXT DEFAULT '0',
    is_used BOOLEAN DEFAULT false,
    organization_unit_id INTEGER NOT NULL,
    office_id INTEGER,
    account_id INTEGER,
    recipient_user_id INTEGER,
    group_of_articles_id INTEGER,
    description TEXT,
    passed_to_finance BOOLEAN DEFAULT false,
    used_in_finance BOOLEAN DEFAULT false,
    is_pro_forma_invoice BOOLEAN DEFAULT false,
    order_file INTEGER,
    receive_file INTEGER[],
    movement_file INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
